/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FlavorsPricingRouteImport } from './routes/flavors-pricing'
import { Route as FlavorsRouteImport } from './routes/flavors'
import { Route as FeaturedRouteImport } from './routes/featured'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CustomOrdersRouteImport } from './routes/custom-orders'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CateringRouteImport } from './routes/catering'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavorsPricingRoute = FlavorsPricingRouteImport.update({
  id: '/flavors-pricing',
  path: '/flavors-pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavorsRoute = FlavorsRouteImport.update({
  id: '/flavors',
  path: '/flavors',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturedRoute = FeaturedRouteImport.update({
  id: '/featured',
  path: '/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomOrdersRoute = CustomOrdersRouteImport.update({
  id: '/custom-orders',
  path: '/custom-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CateringRoute = CateringRouteImport.update({
  id: '/catering',
  path: '/catering',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/faq': typeof FaqRoute
  '/featured': typeof FeaturedRoute
  '/flavors': typeof FlavorsRoute
  '/flavors-pricing': typeof FlavorsPricingRoute
  '/gallery': typeof GalleryRoute
  '/inquiry': typeof InquiryRoute
  '/menu': typeof MenuRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/faq': typeof FaqRoute
  '/featured': typeof FeaturedRoute
  '/flavors': typeof FlavorsRoute
  '/flavors-pricing': typeof FlavorsPricingRoute
  '/gallery': typeof GalleryRoute
  '/inquiry': typeof InquiryRoute
  '/menu': typeof MenuRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catering': typeof CateringRoute
  '/contact': typeof ContactRoute
  '/custom-orders': typeof CustomOrdersRoute
  '/faq': typeof FaqRoute
  '/featured': typeof FeaturedRoute
  '/flavors': typeof FlavorsRoute
  '/flavors-pricing': typeof FlavorsPricingRoute
  '/gallery': typeof GalleryRoute
  '/inquiry': typeof InquiryRoute
  '/menu': typeof MenuRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catering'
    | '/contact'
    | '/custom-orders'
    | '/faq'
    | '/featured'
    | '/flavors'
    | '/flavors-pricing'
    | '/gallery'
    | '/inquiry'
    | '/menu'
    | '/privacy'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catering'
    | '/contact'
    | '/custom-orders'
    | '/faq'
    | '/featured'
    | '/flavors'
    | '/flavors-pricing'
    | '/gallery'
    | '/inquiry'
    | '/menu'
    | '/privacy'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/catering'
    | '/contact'
    | '/custom-orders'
    | '/faq'
    | '/featured'
    | '/flavors'
    | '/flavors-pricing'
    | '/gallery'
    | '/inquiry'
    | '/menu'
    | '/privacy'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CateringRoute: typeof CateringRoute
  ContactRoute: typeof ContactRoute
  CustomOrdersRoute: typeof CustomOrdersRoute
  FaqRoute: typeof FaqRoute
  FeaturedRoute: typeof FeaturedRoute
  FlavorsRoute: typeof FlavorsRoute
  FlavorsPricingRoute: typeof FlavorsPricingRoute
  GalleryRoute: typeof GalleryRoute
  InquiryRoute: typeof InquiryRoute
  MenuRoute: typeof MenuRoute
  PrivacyRoute: typeof PrivacyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavors-pricing': {
      id: '/flavors-pricing'
      path: '/flavors-pricing'
      fullPath: '/flavors-pricing'
      preLoaderRoute: typeof FlavorsPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavors': {
      id: '/flavors'
      path: '/flavors'
      fullPath: '/flavors'
      preLoaderRoute: typeof FlavorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featured': {
      id: '/featured'
      path: '/featured'
      fullPath: '/featured'
      preLoaderRoute: typeof FeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-orders': {
      id: '/custom-orders'
      path: '/custom-orders'
      fullPath: '/custom-orders'
      preLoaderRoute: typeof CustomOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catering': {
      id: '/catering'
      path: '/catering'
      fullPath: '/catering'
      preLoaderRoute: typeof CateringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CateringRoute: CateringRoute,
  ContactRoute: ContactRoute,
  CustomOrdersRoute: CustomOrdersRoute,
  FaqRoute: FaqRoute,
  FeaturedRoute: FeaturedRoute,
  FlavorsRoute: FlavorsRoute,
  FlavorsPricingRoute: FlavorsPricingRoute,
  GalleryRoute: GalleryRoute,
  InquiryRoute: InquiryRoute,
  MenuRoute: MenuRoute,
  PrivacyRoute: PrivacyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
